# Generated by Django 4.2 on 2025-06-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_category_options_remove_recipe_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
